import Navbar from "@/components/Shared/Navbar";
import "../assets/main.scss";
import { Monda } from "next/font/google";
import Footer from "@/components/Shared/Footer";

const monda = Monda({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${monda.className} bg-darkest-blue`}>
        <Navbar />
        <main className="my-[8rem] flex flex-col gap-[4rem]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
